PACKAGE_NAME='ripgrep'
DESCRIPTION='A search tool that combines the usability of ag with the raw speed of grep'
MAINTAINER='Varun Madiath <vamega@gmail.com>'
WEBSITE_URL='https://github.com/BurntSushi/ripgrep'
VCS_URL='https://github.com/BurntSushi/ripgrep.git'
LICENSE="MIT"
VERSION='0.10.0'
REPO="vamega/personal-debian-server/${PACKAGE_NAME}"
DOWNLOAD_URL="https://github.com/BurntSushi/ripgrep/releases/download/${VERSION}/ripgrep_${VERSION}_amd64.deb"
